@startuml crypto
!include .stylesheet.puml

left footer WFJL Crypto Class Diagram

package org.whiteflagprotocol.java.crypto {
    class WfEncryptor {
        +encrypt(String) : String
        +decrypt(String) : String
    }
    enum WfAuthenticationMethod {
        +TOKEN_PRESHARED
    }
    class WfAuthToken {
        +getVerificationData() : String
    }
    enum WfEncryptionMethod {
        +AES_PRESHARED
        +AES_NEGOTIATED
    }
    class WfEncryptionKey {
        +getEncryptionKey() : byte[]
    }
    class WfECDHKeyPair {
        +getPublicKey() : byte[]
        +getSharedKey(byte[]): byte[]
    }
    class WfCryptoUtil <<Utility>> {
        +parseHexString(String) : byte[]
        +toHexString(byte[]) : String
        +hkdf() : byte[]
    }
}

WfEncryptor ..> WfEncryptionKey
WfEncryptionKey --- WfEncryptionMethod
WfAuthToken --- WfAuthenticationMethod
WfEncryptionKey ..> WfCryptoUtil
WfEncryptionKey ..> WfECDHKeyPair
WfAuthToken ..> WfCryptoUtil

@enduml