@startuml crypto
!include .stylesheet.puml

left footer WFJL Crypto Class Diagram

package org.whiteflagprotocol.java.crypto {
    class WfCipher {
        +setContext(byte[])
        +setInitVector(byte[])
        +encrypt(byte[]) : byte[]
        +decrypt(byte[]) : byte[]
    }
    enum WfAuthenticationMethod {
        +TOKEN_PRESHARED
    }
    class WfAuthToken {
        +getVerificationData() : byte[]
    }
    enum WfEncryptionMethod {
        +AES_256_CTR_ECDH
        +AES_256_CTR_PSK
    }
    class WfEncryptionKey {
        +getEncryptionMethod() : WfEncryptionMethod
        +getSecretKey() : byte[]
    }
    class WfECDHKeyPair {
        +getPublicKey() : byte[]
        +getSharedKey(byte[]): byte[]
    }
    class WfCryptoUtil <<Utility>> {
        +convertToByteArray(String) : byte[]
        +convertToHexString(byte[]) : String
        +hkdf() : byte[]
        #hkdfExtract() : byte[]
        #hkdfExpand() : byte[]
    }
}

WfCipher ..> WfEncryptionKey
WfEncryptionKey --- WfEncryptionMethod
WfAuthToken --- WfAuthenticationMethod
WfEncryptionKey ..> WfCryptoUtil
WfEncryptionKey ..> WfECDHKeyPair
WfAuthToken ..> WfCryptoUtil

@enduml