@startuml errors
!include .stylesheet.puml

left footer WFJL Error Class Diagram

class Exception <<Throwable>>

package org.whiteflagprotocol.java.core {
    class WfCoreException
}
Exception <|- WfCoreException

package org.whiteflagprotocol.java.util {
    class WfUtilException
    enum WfUtilException.ErrorType {
        WF_UTIL_ERROR
        WF_JSON_ERROR
    }
    WfUtilException +-- WfUtilException.ErrorType
}
Exception <|-- WfUtilException

package org.whiteflagprotocol.java {
    class WfException
    enum WfException.ErrorType {
        WF_PROTOCOL_ERROR
        WF_METADATA_ERROR
        WF_FORMAT_ERROR
        WF_REFERENCE_ERROR
        WF_AUTH_ERROR
        WF_SIGN_ERROR
        WF_ENCRYPTION_ERROR
    }
    WfException +-- WfException.ErrorType
}
WfCoreException <|- WfException

@enduml