@startuml errors
!include .stylesheet.puml

left footer WFJL Error Class Diagram

package org.whiteflagprotocol.java.core {
    class WfCoreException <<Throwable>>
}

package org.whiteflagprotocol.java {
    class WfException <<Throwable>>
    enum WfException.ErrorType {
        WF_PROTOCOL_ERROR
        WF_METADATA_ERROR
        WF_FORMAT_ERROR
        WF_REFERENCE_ERROR
        WF_AUTH_ERROR
        WF_SIGN_ERROR
        WF_ENCRYPTION_ERROR
    }
    WfException +-- WfException.ErrorType
}

package org.whiteflagprotocol.java.crypto {
    class WfCryptoException <<Throwable>>
}

package org.whiteflagprotocol.java.util {
    class WfUtilException <<Throwable>>
    enum WfUtilException.ErrorType {
        WF_UTIL_ERROR
        WF_JSON_ERROR
    }
    WfUtilException +-- WfUtilException.ErrorType
}

@enduml