@startuml messages
!include .stylesheet.puml

left footer WFJL Message Class Diagram

package org.whiteflagprotocol.java.core {
    class WfMessageCore {
        +type : WfMessageType
        +header : WfMessageSegment
        +body : WfMessageSegment
        +serialize() : String
        +encode() : String
    }
    class WfMessageSegment {
        -fields : WfMessageField[]
        +serialize() : String
        +deserialize(String)
        +encode() : WfBinaryString
        +decode(WfBinaryString)
    }
    class WfMessageField {
        +name : String
        +pattern : Pattern
        +encoding : Encoding
        +startByte : int
        +endByte : int
        -value : String
        +encode() : WfBinaryString
        +decode(WfBinaryString) : String
    }
    class WfMessageCreator {
        __
        +create()
        ..
        +type(WfMessageType)
        +map(Map, Map)
        +deserialize(String)
        +decode(String)
        +compile(String[])
    }
    enum WfMessageType {
        A
        K
        T
        F
        R
        P
        E
        S
        D
        I
        M
        Q
    }
    class WfMessageDefinitions <<Utility>> {
        #headerFields : WfMessageField[]
        #authenticationFields : WfMessageField[]
        #cryptoFields : WfMessageField[]
        #testFields : WfMessageField[]
        #freetextFields : WfMessageField[]
        #resourceFields : WfMessageField[]
        #signsignalFields : WfMessageField[]
        #createRequestFields() : WfMessageField[]
    }
    class WfMessageCodec <<Utility>> {
        +encodeString(String) : WfBinaryString
        +decodeString(WfBinaryString) : String
        +encodeField(WfMessageField) : byte[]
        +decodeField(byte[]) : String
    }
    enum Encoding {
        BIN
        DEC
        HEX
        UTF8
        DATETIME
        DURATION
        LAT
        LONG
    }
    class WfBinaryString <<DataType>>
    class WfBinaryBuffer <<DataType>>
}

package org.whiteflagprotocol.java.util {
    class WfJsonMessage {
        +toJson() : String
        +create(String)
    }
}

package org.whiteflagprotocol.java {
    class WfMessage {
        -metadata : HashMap<>
        +type : WfMessageType
        +header : WfMessageSegment
        +body : WfMessageSegment
        +type(String) : WfMessage
        +copy(WfMessage) : WfMessage
        +deserialize(String) : WfMessage
        +deserializeJson(String) : WfMessage
        +decode(String) : WfMessage
        +compile(String[]) : WfMessage
        +encode() : String
        +toJson() : String
    }
}

WfJsonMessage <. WfMessage

WfMessage --|> WfMessageCore
WfMessage ---> WfMessageCreator: uses

WfMessageCore --> WfMessageType
WfMessageCore *-- "2" WfMessageSegment
WfMessageSegment *-- "*" WfMessageField
WfMessageCodec <. WfMessageField
Encoding -+ WfMessageCodec

WfMessageCreator -> WfMessageCore: creates
WfMessageCreator ..> WfMessageType
WfMessageCreator ..> WfMessageSegment

WfMessageType --> WfMessageDefinitions
WfMessageDefinitions --> WfMessageField

@enduml