@startuml overview
!include .stylesheet.puml

left footer WFJL Overview Class Diagram

package org.whiteflagprotocol.java {
    class WfMessage {
        -metadata : HashMap<>
        ..
        -originator : WfParticipant
        -recipient : WfParticipant
        ..
        +type : WfMessageType
        +header : WfMessageSegment
        +body : WfMessageSegment
        __
        +type(String) : WfMessage
        +copy(WfMessage) : WfMessage
        +deserialize(String) : WfMessage
        +deserializeJson(String) : WfMessage
        +decode(String) : WfMessage
        +compile(String[]) : WfMessage
        ..
        +encode() : WfBinaryBuffer
        +toJson() : String
    }

    class WfParticipant <<interface>> {
        +isSelf() : boolean
        ..
        +getAddress() : String
        +getBinaryAddress() : byte[]
        +getAuthURL() : URL
        +getAuthToken() : WfAuthToken
        +getEcdhKeyPair() : WfECDHKeyPair
        +getEcdhPublicKey() : ECPublicKey
        +getSharedKey() : WfEncryptionKey
    }
}

@enduml