name: Windows Test
on:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        java-version: [8, 11, 15]
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
        ava-package: jdk
        architecture: x64
    - name: Run tests
      run: ./gradlew test
